services:
  app:
    container_name: moviething
    build: 
      context: .
      dockerfile: Dockerfile
    image: grahams/moviething:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MOVIETHING_SQL_HOST=${MOVIETHING_SQL_HOST}
      - MOVIETHING_SQL_USER=${MOVIETHING_SQL_USER}
      - MOVIETHING_SQL_PASS=${MOVIETHING_SQL_PASS}
      - MOVIETHING_SQL_DB=${MOVIETHING_SQL_DB}
      - MOVIETHING_OMDB_API_KEY=${MOVIETHING_OMDB_API_KEY}
      - MOVIETHING_VALID_API_KEY=${MOVIETHING_VALID_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mariadb

networks:
  mariadb:
    external: true
