version: "3.3"
services:
  moviething:
    container_name: moviething
    build:
      context: .
      dockerfile: Dockerfile
    image: grahams/moviething:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MOVIETHING_SQL_HOST=${MOVIETHING_SQL_HOST}
      - MOVIETHING_SQL_USER=${MOVIETHING_SQL_USER}
      - MOVIETHING_SQL_PASS=${MOVIETHING_SQL_PASS}
      - MOVIETHING_SQL_DB=${MOVIETHING_SQL_DB}
      - MOVIETHING_OMDB_API_KEY=${MOVIETHING_OMDB_API_KEY}
      - MOVIETHING_VALID_API_KEY=${MOVIETHING_VALID_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      # Exclude node_modules from volume mounting
      - /app/node_modules
